config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  
  get 'index'                 => 'static_pages#index'
  get 'about'                 => 'static_pages#about'
  get 'gallery'               => 'static_pages#gallery'
  get 'consignment'           => 'static_pages#consignment'
  get 'contact'               => 'static_pages#contact'
  
  get 'contact'               => 'static_pages#contact'
  
  get 'upload_photo'          => 'application#uploadPhoto'
  get 'edit_gallery'          => 'static_pages#edit_gallery'
  get 'destroy_photo'         => 'photos#destroy'
  get 'admin'                 => 'static_pages#admin'
  get 'admin_login'           => 'application#admin_login'
  get 'admin_logout'          => 'application#admin_logout'
  get 'submit_email'          => 'application#submitEmailAddress'
  get 'mailing_list'          => 'static_pages#mailing_list'
  get 'download_mailing_list' => 'application#download_mailing_list'
  
  get 'facebook'              => 'application#routeToFacebook'
  get 'instagram'             => 'application#routeToInstagram'
  get 'twitter'               => 'application#routeToTwitter'
  
  resources :photos, only: [:new, :create, :destroy]

end

app/models/email_address.rb
class EmailAddress < ActiveRecord::Base
    
    # Regular Expression to filter for only those emails of form: "user@domain.extension":
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    
    before_save :downcase_email
    
    validates :email,
        presence: true,
        length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        
    private
    
        def downcase_email
           self.email = email.downcase 
        end
        
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    ###### Uploaders ######
    mount_uploader :image, PhotoUploader
    
    ###### Validations ######
    validates :image,
        presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :redirect_if_not_admin, only: [:download_mailing_list]
  protect_from_forgery with: :exception
  helper_method :user_is_admin
  require 'tempfile'
  
  def download_mailing_list
    @email_addresses = EmailAddress.all
    @record_limit = @email_addresses.size

    file = Tempfile.new(["offtherack-mailing-list-", ".csv"])
    #...
      @counter = 1
      @email_addresses.each do |record|
        if @counter == @record_limit
          file.puts(record.email)
        else
          file.puts(record.email + ", ")
        end
        @counter += 1
      end
    #...
    file.rewind
    send_file file.path
    file.close
  end
  
  def admin_login
    @checktext = params[:checktext]
    if checktextMatchesAdmin(@checktext)
      cookies['admin_key'] = @checktext
      flash[:success] = "Successful Login!"
    else
      flash[:danger] = "Unsuccessful login."
    end
    redirect_to admin_path
  end
  
  def admin_logout
    cookies['admin_key'] = ""
    flash[:success] = "Logged Out."
    redirect_to root_path
  end
  
  def submitEmailAddress
    @email = EmailAddress.new
    @email.email = params[:email]
    
    if EmailAddress.find_by(email: @email.email) != nil
      flash[:warning] = "Your Email Address is Already on Record"
      redirect_to contact_path
    elsif @email.save
      flash[:success] = "Email Address Submitted!"
      redirect_to contact_path
    else
      flash[:danger] = "Unable to Submit Email Address"
      redirect_to contact_path
    end
  end
  
  def routeToFacebook
    redirect_to "https://www.facebook.com/OffTheRackClothes"
  end
  
  def routeToInstagram
    redirect_to "https://www.instagram.com/offtherack256/"
  end
  
  def routeToTwitter
    redirect_to "https://www.twitter.com/offtherack256"
  end
  
  def user_is_admin
    if checktextMatchesAdmin(cookies['admin_key'])
      return true
    else
      return false
    end
  end
  
  def redirect_if_not_admin
    if checktextMatchesAdmin(cookies['admin_key'])
      # Good to Go
    else
      flash[:danger] = "Unauthorized Resource."
      redirect_to root_path
    end
  end
  
  private
  
      def checktextMatchesAdmin(str)
         return str == ENV['ADMIN_KEY']
      end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :redirect_if_not_admin, only: [:new, :create, :destroy]
  
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(photo_params)
    
    if user_is_admin
      if @photo.save
        flash[:success] = "Photo Uploaded!"
        redirect_to edit_gallery_path
      else
        flash[:danger] = "Unable to Upload Photo"
        redirect_to new_photo_path
      end
    else
      flash[:danger] = "Unauthorized Resource"
      redirect_to gallery_path
    end
  end

  def destroy
    if Photo.find(params[:id]).destroy
      flash[:success] = "Photo Deleted!"
      redirect_to edit_gallery_path
    else
      flash[:danger] = "Unable to Delete Photo"
      redirect_to edit_gallery_path
    end
  end
  
  private
  
       def photo_params
         params.require(:photo).permit(:image)
       end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :redirect_if_not_admin, only: [:edit_gallery, :mailing_list]
  
  def index
  end

  def about
  end

  def edit_gallery
    @photos = Photo.all
  end

  def gallery
    @photos = Photo.all
  end

  def mailing_list
    @addresses = EmailAddress.all
  end

  def consignment
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def bootstrap_class_for flash_type
        { success: "alert-success", danger: "alert-danger", alert: "alert-warning", warning: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
    end
    
    def flash_messages(opts = {})
        flash.each do |msg_type, message|
            concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in", id: "alert-override") do 
                concat content_tag(:button, '×'.html_safe, class: "close", data: { dismiss: 'alert' })
                concat message 
            end)
        end
        nil
    end
    
end

app/helpers/photos_controller_helper.rb
module PhotosControllerHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
/ Footer

%section{:id => "socialMediaBar"}
  %div.container
    %div.row
      %hr
      #footer.p-y-4
        %img= image_tag "otr_logo_small.png", id: "footerLogo"
      = link_to facebook_path, class: "btn" do
        %i.fa.fa-facebook-square.fa-5x{"aria-hidden" => "true"}
      = link_to instagram_path, class: "btn" do
        %i.fa.fa-instagram.fa-5x{"aria-hidden" => "true"}
      = link_to twitter_path, class: "btn" do
        %i.fa.fa-twitter-square.fa-5x{"aria-hidden" => "true"}
#footer.p-y-4
  Copyright © Off The Rack 2017. All Rights Reserved.
  = link_to "Admin Login", admin_path
  %p <a href="tel:256-886-8304"> 256-886-8304</a>

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .nav-container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#offtherack-nav-links", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Off The Rack Boutique", root_path, class: "navbar-brand", id: "serrifize"
    #offtherack-nav-links.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "How To Consign", consignment_path, id: "serrifize"
        %li= link_to "Gallery", gallery_path, id: "serrifize"
        %li= link_to "About", about_path, id: "serrifize"
        %li= link_to "Contact: 256-886-8304", contact_path, id: "serrifize"
        - if user_is_admin
          %li= link_to "Admin", admin_path, id: "serrifize"

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
	%head
		/ Global site tag (gtag.js) - Google Analytics
		%script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-122351659-3"}
		:javascript
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', 'UA-122351659-3');
		/ Meta data
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title
			Off The Rack #{yield(:title)}
		%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
		= render 'layouts/shim'
	%body#main-body
		= render 'layouts/navbar'
		= flash_messages
		/
		/this line is where any view is rendered when the associated controller method is called
		= yield
		/
		= render 'layouts/footer'
		= debug(params) if Rails.env.development?

app/views/photos/create.html.haml
%h1 PhotosController#create
%p Find me in app/views/photos_controller/create.html.haml

app/views/photos/destroy.html.haml
%h1 PhotosController#destroy
%p Find me in app/views/photos_controller/destroy.html.haml

app/views/photos/new.html.haml
- provide(:title, '| New Photo')
%section{:id => "pageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 New Photo
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div{:class => "pageBarTextBlock-b"}
        = form_for(@photo) do |f|
          %p.leftify
            = f.file_field :image
          %p.leftify
            = f.submit "Submit", class: "btn btn-default"

app/views/shared/_error_message.html.haml
- if object.errors.any?
  %div
    %div
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/about.html.haml
- provide(:title, '| About')
%section{:id => "pageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 About
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div{:class => "col-lg-8 col-md-8 col-sm-8 col-lg-offset-2 col-md-offset-2 col-sm-offset-2"}
        %p Rachel Rutledge, owner of Off The Rack Boutique, had a vision to open a Formals/Semi-Formals Consignment Store after visiting one while on vacation! OTR started in the sun-room of her home in September of 2016 and quickly outgrew the space. OTR Boutique is now located at 703 Pratt Ave NW Suite 304 in Huntsville, just one mile from downtown. Along with its new location came more space. In addition to offering consignments on formals, Off The Rack Boutique also has a collection of casual clothes including businesswear, sweaters, sundresses, shoes, and accesories. Here's our stance...
%div.container.centerfy
  %div.row
    %div{:class => "col-lg-4 col-md-4 col-sm-4 col-lg-offset-2 col-md-offset-2 col-sm-offset-2"}
      %p
        %em You bought beautiful BOUTIQUE clothing and now that it's time to clean out those closets, what are you going to do with last years items? Consign  them at Off The Rack Boutique!
    %div{:class => "col-lg-4 col-md-4 col-sm-4"}
      %p 
        %em Off The Rack is a boutique-style Consignment Store serving teens and women - casual wear, formals, semi-formals, shoes, designer hand bags and accessories.
%section{:id => "pageBarTwo"}
  %div.container
    %div.row
      %div{:class => "pageBarTextBlock-b"}
        %p We accept conisgnments by APPOINTMENT only. Click #{link_to 'How To Consign', consignment_path} to find out more!
        = link_to "Qustions? Contact us!", contact_path, class: "bigFont"

app/views/static_pages/admin.html.haml
%section{:id => "homepageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 Admin
        %h2 Admin Pages
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div{:class => "pageBarTextBlock-b bigFont"}
        - if user_is_admin
          %p
            %span= link_to "Edit the Gallery", edit_gallery_path, class: "btn btn-default"
            %span= link_to "Upload to Gallery", new_photo_path, class: "btn btn-default"
          %p
            %span= link_to "View Mailing List", mailing_list_path, class: "btn btn-default"
            %span= link_to "Download Mailing List", "", class: "btn btn-default", :onclick => "download_list(); return false"
          %p.centerfy= link_to "Logout", admin_logout_path, class: "btn btn-default"
        - else
          = form_tag "/admin_login", method: "get" do
            = label_tag :checktext, "Password:"
            = text_field_tag :checktext
            = submit_tag "Submit", class: "btn btn-default"

app/views/static_pages/consignment.html.haml
- provide(:title, '| Consign')
%section{:id => "pageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 How To Consign
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div{:class => "col-lg-6 col-md-6 col-sm-6"}
        %p Thank you for your interest in consigning with Off The Rack! We accept new and gently used items that are currently in-style and like-new condition. Items should be in excellent condition with buttons, hooks, straps, and zippers in working order and free from debris and odor. Acceptable clothing will be free from spots/stains, pulls and rips. Items must be received on hangers and pressed if needed. OTR will set up your personal account, label items and present you with a consignment agreement (including tracking list for your convenience). Items will be chosen based on ability to sell and those which will compliment our existing inventory. Please note, all items may not be accepted for reasons listed above. <b> Consigning items is by appointment only</b>, so give us a call at <a href="tel:256-886-8304"> 256-886-8304</a> today to schedule a time to come in. 
      %div{:class => "col-lg-6 col-md-6 col-sm-6"}
        %p Accepted items will be available for sale for 6 months. Items will be priced between 30-40% of retail prices. Inventory is computerized. The consignor and OTR will both receive 50% of the selling price. Upon sale, payment is applied directly into your account and will remain there until you request payout. Consignors must contact OTR to inquire about items that have sold.
        = link_to "Qustions? Contact us!", contact_path, class: "bigFont"
%section{:id => "pageBarTwo"}
  %div.container
    %div.row
      %div{:class => "pageBarTextBlock-a"}
        %p
          %em Off The Rack is not responsible for the loss of consigned articles through fire, theft, vandalism, or natural disaster. All sales are final. Off The Rack has a NO-RETURN policy.  
%section{:id => "pageBarTwo"}
  %div.container
    %div.row
      %div{:class => "pageBarTextBlock-b"}
        %p Consignors are welcomed and encouraged to share our website and/or social media sites with others! The more people aware of OTR, the more likely your items will sell in a timely manner. So spread the word and let’s make some sales! 

app/views/static_pages/contact.html.haml
- provide(:title, '| Contact')
%section{:id => "pageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 Contact
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div{:class => "col-lg-4 col-md-4 col-sm-4 centerfy"}
        %h1 Regular Business Hours:
        // %p <b><font color="red">Extended Tuesdays for Homecoming season!</font></b>
        // %p <b>Tuesday: 12pm-8pm</b>
        %p Tuesday - Friday: 10am-5:30pm
        %p Saturday: 10am-2pm
        %p Sunday - Monday: Closed
        // Temporary Business Hours
        %p
        %p <b><font color="orange">Thanksgiving Hours</font></b>
        %p <b><font color="brown">Wed Nov 21 10am-2pm</font></b>
        %p <b><font color="brown">Thurs Nov 22 CLOSED</font></b>
        //%p <b>Tuesday</b>: 12pm-8pm
        //%p 11am-4pm
        //%p
        // Special Business Hours
        //%h2 <font color="red">We will be CLOSED on BOTH Tuesday and Wednesday this week in celebration of <font color="blue">July 4th</font> - Enjoy the holiday!</font>
        //%p 11am-3pm
        //%p
        //%h2 Business Hours
        //%p (16 Jan - 20 Jan)
        //%p Wednesday - Friday: 11am-4:30pm
        //%p Saturday: 10am-2pm
        //
      %div{:class => "col-lg-4 col-md-4 col-sm-4 centerfy"}
        %h1 Contact Us:
        %p Rachel Rutledge
        %p <a href="mailto:rachel@offtherack256.com"> rachel@offtherack256.com </a>
        %p <a href="tel:256-886-8304"> 256-886-8304</a>
      %div{:class => "col-lg-4 col-md-4 col-sm-4 centerfy"}
        %h1 Learn More:
        = form_tag("/submit_email", method: "get") do
          = label_tag :email, "Join Our Mailing List!"
          %p
            = email_field_tag :email
            = submit_tag "Submit", class: "btn btn-default"
%h1 Map:
%iframe{:allowfullscreen => "", :frameborder => "0", :height => "350px", :src => "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6557.260529040903!2d-86.594281!3d34.739713!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9e180b5e69329029!2sOff+The+Rack+Boutique!5e0!3m2!1sen!2sus!4v1540402591621", :style => "border:0", :width => "100%"}

app/views/static_pages/edit_gallery.html.haml
- provide(:title, '| Edit Gallery')
%section{:id => "pageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 Gallery
        %h2 Admin Page
%section{:id => "photoUpload"}
  %span= link_to "Upload Image", new_photo_path, class: "btn btn-default"
%p.centerfy Careful! You'll delete any photo you click here.
%section#gallery
  .container
    .row
      .col-lg-12.col-md-12.col-sm-12
        #gallerySLide.gallery_area
          - @photos.each do |img|
            %a{:href => destroy_photo_path(:id => img.id)}
              %img.gallery_img{:alt => "img", :src => img.image_url(:small)}
              %span.view_btn Delete

app/views/static_pages/gallery.html.haml
- provide(:title, '| Gallery')
%section{:id => "pageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 Gallery
%section#gallery
  .container
    .row
      .col-lg-12.col-md-12.col-sm-12
        #gallerySLide.gallery_area
          - @photos.each do |img|
            %a{:href => img.image_url}
              %img.gallery_img{:alt => "img", :src => img.image_url(:small)}
              %span.view_btn View
%section{:id => "photoUpload"}
  %span= link_to "Upload", new_photo_path, class: "btn btn-default"

app/views/static_pages/index.html.haml
%section{:id => "homepageTitle"}
  %div{:id => "homepageHoursBox", :class => "col-lg-3 col-md-3 col-sm-3"}
    .boldify Regular Business Hours: 
    .boldify Tuesday - Friday: 10am-5:30pm
    .boldify Saturday: 10am-2pm
    .boldify Sunday - Monday: Closed
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-12 col-md-12 col-sm-12"}
        %img= image_tag "otr_logo_small.png", id: "homepageLogo"
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div{:class => "pageBarTextBlock-b bigFont"}
        %p A Boutique-Style Consignment Store serving teens and women - casual wear, formals, semi-formals, shoes, designer hand bags and accessories.
%section{:id => "pageBarThree"}
  %div.container
    %div.row
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "600px", :src => "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6557.260529040903!2d-86.594281!3d34.739713!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9e180b5e69329029!2sOff+The+Rack+Boutique!5e0!3m2!1sen!2sus!4v1540402591621", :style => "border:0", :width => "100%"}
%section{:id => "homepageTwo"}
  %div.container
    %div.row
      %div{:class => "col-lg-6 col-md-6 col-sm-6"}
      %div{:class => "col-lg-4 col-md-4 col-sm-4"}
        %p Consignment made easy.

app/views/static_pages/mailing_list.html.haml
- provide(:title, '| Mailing List')
%section{:id => "homepageTitle"}
  %div.container
    %div.row
      %div{:id => "titleBox", :class => "col-lg-6 col-md-6 col-sm-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3"}
        %h1 Mailing List
        %h2 Admin Page
%section{:id => "pageBarOne"}
  %div.container
    %div.row
      %div
        %p.centerfy= link_to "Download List", "", :onclick => "download_list(); return false"
      %div{:class => "pageBarTextBlock-b bigFont"}
        -@addresses.each do |ad|
          =ad.email
          %br